version: '3.0'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-example
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports: 
      - "8080:8080"
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-example
    #  - prometheus-example
    depends_on:
      - jaeger
      #- prometheus
  #prometheus:
    #image: 'prom/prometheus:latest'
    #ports:
    #- '9090:9090'
    #networks:
   #   - prometheus-example
    #volumes:
    #- './prometheus.yml:/etc/prometheus/prometheus.yml'

networks:
  jaeger-example:
  #prometheus-example:
